export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const FETCH_POST = 'FETCH_POST'
export const DELETE_POST = 'DELETE_POST'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const FETCH_COMMENT ='FETCH_COMMENT'
